language: ruby
sudo: false
cache: bundler
rvm:
- 2.1
- 2.0.0
- 1.9.3
before_script: bundle update
script: script/cibuild
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
    - irc.freenode.org#jekyll
    template:
    - '%{repository}#%{build_number} (%{branch}) %{message} %{build_url}'
  email:
    on_success: never
    on_failure: never
